spring:
  thymeleaf:
   cache: false
   check-template-location: true
   prefix: classpath:/templates/
   suffix: .html
   enabled: true
  application:
    name: board_study
  profiles:
    active: local
  datasource:
    #mariadb는 자신이 사용하고자 하는 스키마를 입력해야지 들어가짐.
    url: jdbc:mariadb://localhost:3306/board_study
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-board_study
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        hibernate:
        "[format_sql]": "true"
        "[hbm2ddl.auto]": "update"
        "[implicit_naming_strategy]": "org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy"
        #"[physical_naming_strategy]": org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    open-in-view: false
    show-sql: true

#log4j 설정
logging:
  level:
    root: INFO

server:
  port: ${myapp.port:8989}